name: klaket_cine
description: A new Flutter streaming movies and series application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^6.3.3
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  supabase_flutter: ^2.5.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/Font/Cairo/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Font/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/Font/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/Font/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/Font/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/Font/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/Font/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/Font/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/Font/Cairo/Cairo-Black.ttf
          weight: 900
